import React from 'react';
import { Breadcrumbs } from '../components/common/Breadcrumbs';
import { SEOHead } from '../components/common/SEOHead';
import { FileText, CheckCircle2, AlertTriangle, Scale, ShieldAlert } from 'lucide-react';

export const TermsPage: React.FC = () => {
  const seoData = {
    title: 'Terms of Use | StatKick',
    description: 'Terms and conditions governing the use of StatKick football statistical calculators, tools, and analytical models.',
    canonicalPath: '/terms',
  };

  return (
    <div className="w-full pb-8">
      <SEOHead {...seoData} />
      <Breadcrumbs items={[{ label: 'Terms of Use' }]} />

      <header className="my-6">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-green-50 text-green-700 border border-green-200 mb-3">
          <FileText className="w-3.5 h-3.5" />
          Legal Terms
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-gray-900">
          Terms of Use
        </h1>
        <p className="mt-2 text-xs sm:text-sm text-gray-500">
          Last Updated: February 2026 • StatKick Independent Football Analytics
        </p>
      </header>

      {/* Editorial Terms Documentation */}
      <article className="prose max-w-none text-xs sm:text-sm text-gray-700 space-y-6 leading-relaxed">
        <div className="rounded-2xl border border-gray-200 bg-white p-6 sm:p-8 space-y-4 shadow-2xs">
          <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
            <Scale className="w-4 h-4 text-green-600" />
            1. Acceptance of Terms
          </h2>
          <p>
            By accessing or using the StatKick website and its 21 football statistical calculators, you agree to be bound by these Terms of Use and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
          </p>
        </div>

        <div className="rounded-2xl border border-gray-200 bg-white p-6 sm:p-8 space-y-4 shadow-2xs">
          <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-green-600" />
            2. Nature of Analytical Calculators & Informational Disclaimer
          </h2>
          <p>
            All tools, formulas, ratings, transfer estimates, points-needed simulations, and tactical analysis generated by StatKick are provided for <strong>educational, informational, and recreational entertainment purposes only</strong>.
          </p>
          <ul className="list-disc list-inside space-y-2 text-gray-600 pl-2">
            <li>
              <strong>No Gambling or Financial Advice:</strong> Outputs from our calculators must never be construed as sports betting advice, financial guarantees, or contractual valuation endorsements.
            </li>
            <li>
              <strong>Mathematical Modeling:</strong> Calculations are based on mathematical frameworks, publicly acknowledged analytical conventions, and user-provided numerical inputs. Actual sports performances involve inherent variance.
            </li>
          </ul>
        </div>

        <div className="rounded-2xl border border-gray-200 bg-white p-6 sm:p-8 space-y-4 shadow-2xs">
          <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-green-600" />
            3. Permitted Use & Intellectual Property
          </h2>
          <p>
            You are granted a personal, non-exclusive, non-transferable license to utilize the calculators for personal research, grassroots team management, football writing, and fantasy league planning. You may cite or share calculation summaries with attribution to StatKick.
          </p>
          <p>
            You agree not to scrape, reverse-engineer, or systematically extract the website layout, design assets, or styling code without prior authorization.
          </p>
        </div>

        <div className="rounded-2xl border border-gray-200 bg-white p-6 sm:p-8 space-y-4 shadow-2xs">
          <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-green-600" />
            4. Limitation of Liability & Governing Law
          </h2>
          <p>
            In no event shall StatKick, its creators, or contributors be held liable for any damages (including, without limitation, damages for loss of data, fantasy league rank outcomes, or betting losses) arising out of the use or inability to use the materials on StatKick.
          </p>
        </div>
      </article>
    </div>
  );
};
